/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package basiclibrary;

public class Library {
    public static void main(String[] args) {
        System.out.println("Hello world!");
        int[] result = roll(4);
        for(int c = 0; c < result.length; c+=1){
            System.out.println(result[c]);
        }
        boolean isDuplicate = containsDuplicates(result);
        System.out.println(isDuplicate);
        int[][] weeklyMonthTemperatures = {
                {66, 64, 58, 65, 71, 57, 60},
                {57, 65, 65, 70, 72, 65, 51},
                {55, 54, 60, 53, 59, 57, 61},
                {65, 56, 55, 52, 55, 62, 57}
        };
        for(int i = 0; i < weeklyMonthTemperatures.length; i+=1){
            System.out.println(calculateAvarage(weeklyMonthTemperatures[i]));
        }
        System.out.println("-------");
        int[] minAvgArr = calculateMinAvg(weeklyMonthTemperatures);
        for(int y = 0; y < minAvgArr.length; y+=1){
            System.out.println(minAvgArr[y]);
        }
    }

    public static int[] roll(int n){
        int[] result = new int[n];
        for(int i = 0; i < n; i+=1){
            result[i] = (int)Math.floor(Math.random()*(6-1+1)+1);
        }
        return result;
    }

    public static boolean containsDuplicates(int[] arr){
        for(int i = 0; i < arr.length; i+=1){
            for(int c = 0; c < arr.length; c+=1){
                if (i != c && arr[i] == arr[c]){
                    return true;
                }
            }
        }
        return false;
    }

    public static float calculateAvarage(int[] arr){
        float avg = 0.0f;
        for(int i = 0; i < arr.length; i+=1){
            avg += arr[i];
        }
        return avg/arr.length;
    }

    public static int[] calculateMinAvg(int[][] arr){
        float[] avgArr = new float[arr.length];
        for(int i = 0; i < arr.length; i+=1){
            avgArr[i] = calculateAvarage(arr[i]);
        }
        int minIdx = getMin(avgArr);
        return arr[minIdx];
    }

    public static int getMin(float[] arr){
        float min;
        int idx;
        if(arr.length < 2){
            return 0;
        }else{
            min = arr[0];
            idx = 0;
        }
        for(int i = 0; i < arr.length; i+=1){
            if(arr[i] < min){
                min = arr[i];
                idx = i;
            }
        }
        return idx;
    }
}
