/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package inheritance;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class LibraryTest {
    @Test void someLibraryMethodReturnsTrue() {
        Library classUnderTest = new Library();
        //assertTrue(classUnderTest.someLibraryMethod(), "someLibraryMethod should return 'true'");

    }
    @Test public void testres(){
        Restaurant newInstanceRestaurant1=new Restaurant("Thaer Restaurant",10,"$$$");
        String resultTest="Restaurant Name: Thaer Restaurant with rate: 10 and price category: $$$";
        assertEquals(resultTest,newInstanceRestaurant1.toString());
    }
    @Test public void testReview(){
        Review newInstanceReview=new Review("bad","thaer",1);
        String resultTest="Author Name: thaer said: bad and his rate was: 1";
        assertEquals(resultTest,newInstanceReview.toString());
    }
    @Test public void testadd(){
        Restaurant newInstanceRestaurant1=new Restaurant("Thaer Restaurant",10,"$$$");
        Review newInstanceReview=new Review("not good","Thaer",1);
        newInstanceRestaurant1.addReview(newInstanceReview);
        String resultTest="Restaurant Name: Thaer Restaurant with rate: 1 and price category: $$$";
        assertEquals(resultTest,newInstanceRestaurant1.toString());
    }
}